### ISSUE TITLE
Notification is not working

### ISSUE THREAD

**Issue by W0tch3r** [WojRep/Check_MK-SIGNAL_Notification#1]
Firstly, thanks for the checkmk plugin. 

I have done everything according to the instructions, but the notification via signal does not work.

I have entered a phone number in the pager address and also tested it with a group ID, but it does not work. Do I have to define an additional rule so that the notification takes place via signal?

Best regards

**Comment by WojRep** [comment]
Hello, 

I haven't checked this code for a long time, Signal periodically changed the calling of its applications to expand its applications, you would have to check whether all the calling switches match and whether the CLI sends you messages via Signal. If everything works with the CLI, there is most likely something wrong with changing the command call in the python code.


Wojciech Repiński
***@***.***

**Comment by W0tch3r** [comment]
Thanks for the fast reply. 

Over the Cli i can send messages and also in the group via the ID.

Is it neccessary to create a notification rule in checkmk?

**Comment by W0tch3r** [comment]
The problem is that, when i want to create a new notification rule, the method to use signal is not shown to me.
